//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FPBMTTC_FinalC_M_vs2017_ServiceAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonalData
    {
        public int uId { get; set; }
        public string ca_serial_number { get; set; }
        public int ca_id { get; set; }
        public string caPriKey { get; set; }
        public string caPubkey { get; set; }
        public bool caEnable { get; set; }
    
        public virtual User User { get; set; }
        public virtual X509Certificate X509Certificate { get; set; }
    }
}
